#!/usr/bin/env bash
# This script transfers a file from the client to a specified server using scp.

# Check if the number of parameters is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Use scp to transfer the file
scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"

# Check if the scp command was successful
if [ $? -eq 0 ]; then
    echo "File transferred successfully to $USERNAME@$SERVER_IP:~/"
else
    echo "File transfer failed."
fi
