#!/usr/bin/env bash
# Install Nginx
apt-get update -y
apt-get install nginx -y

# Ensure Nginx is listening on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Modify the default Nginx page
echo "Holberton School for the win!" > /var/www/html/index.html

# Ensure the Nginx service is reloaded without using systemctl
nginx -s reload

# Output success message
echo "Nginx has been installed and configured!"

